#define LETTER_A 1
#define LETTER_B 2
#define LETTER_C 3
#define LETTER_D 4
#define LETTER_E 5
#define LETTER_F 6
#define LETTER_G 7
#define LETTER_H 8
#define LETTER_I 9
#define LETTER_J_10
#define LETTER_K 11
#define LETTER_L 12
#define LETTER_M 13
#define LETTER_N 14
#define LETTER_O 15
#define LETTER_P 16
#define LETTER_Q 17
#define LETTER_R 18
#define LETTER_S 19
#define LETTER_T 20
#define LETTER_U 21
#define LETTER_V 22
#define LETTER_W 23
#define LETTER_X 24
#define LETTER_Y 25
#define LETTER_Z 26

#define LETTER_a 32
#define LETTER_b 33
#define LETTER_c 34
#define LETTER_d 35
#define LETTER_e 36
#define LETTER_f 37
#define LETTER_g 38
#define LETTER_h 39
#define LETTER_i 40
#define LETTER_j 41
#define LETTER_k 42
#define LETTER_l 43
#define LETTER_m 44
#define LETTER_n 45
#define LETTER_o 46
#define LETTER_p 47
#define LETTER_q 48
#define LETTER_r 49
#define LETTER_s 50
#define LETTER_t 51
#define LETTER_u 52
#define LETTER_v 53
#define LETTER_w 54
#define LETTER_x 55
#define LETTER_y 56
#define LETTER_z 57
