//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_titleship_H
#define METASPRITE_titleship_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define titleship_TILE_ORIGIN 0
#define titleship_TILE_W 8
#define titleship_TILE_H 8
#define titleship_WIDTH 160
#define titleship_HEIGHT 48
#define titleship_TILE_COUNT 120
#define titleship_PALETTE_COUNT 1
#define titleship_COLORS_PER_PALETTE 4
#define titleship_TOTAL_COLORS 4
#define titleship_MAP_ATTRIBUTES 0

BANKREF_EXTERN(titleship)

extern const palette_color_t titleship_palettes[4];
extern const uint8_t titleship_tiles[1920];

extern const unsigned char titleship_map[120];

#endif
